name: CI Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: 'Test Jupyter Notebooks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install pipenv
        env:
          PIPENV_NOSPIN: 'true'
          WORKON_HOME: ~/.pipenv/virtualenvs
          PIPENV_CACHE_DIR: ~/.pipenv/pipcache
        run: pip install pipenv
      - name: Build and Test
        env:
          PIPENV_NOSPIN: 'true'
          WORKON_HOME: ~/.pipenv/virtualenvs
          PIPENV_CACHE_DIR: ~/.pipenv/pipcache
        run: |
          pipenv install --dev
          # pipenv run py.test --nbval-lax -n auto --dist loadscope